CREATE DATABASE IF NOT EXISTS LOCADORA;

USE LOCADORA;

CREATE TABLE IF NOT EXISTS LOCADORA.CLIENTE
(
	ID_CLIENTE INT,
    NOME_COMPLETO VARCHAR(100),
    NUM_TELEFONE VARCHAR(11),
    DESC_EMAIL VARCHAR(100),
    DATA_NASCIMENTO DATE,
    PRIMARY KEY (ID_CLIENTE)
);

ALTER TABLE LOCADORA.CLIENTE
ADD COLUMN NUM_CPF CHAR(11);


CREATE TABLE IF NOT EXISTS LOCADORA.CARROS
(
	ID_CARROS INT,
    MODELO VARCHAR(50),
    MARCA VARCHAR(30),
    ANO YEAR,
    COR VARCHAR(20),
    PLACA VARCHAR(10) NOT NULL,
    VALOR DECIMAL(10,2),
    PRIMARY KEY (ID_CARROS)
);


                             